export type Book = {
  name: string
  filename: string
}

export type Testament = {
  id: string
  label: string
  books: Array<Book>
}

export const dataSource: Testament[] = [
  {
    id: 'old-testament',
    label: 'Cựu Ước',
    books: [
      { name: 'SÁNG THẾ', filename: '1. SÁNG THẾ.JSON' },
      { name: 'XUẤT HÀNH', filename: '2. XUẤT HÀNH.JSON' },
      { name: 'LÊ-VI', filename: '3. LÊ-VI.JSON' },
      { name: 'DÂN SỐ', filename: '4. DÂN SỐ.JSON' },
      { name: 'PHỤC TRUYỀN LUẬT LỆ', filename: '5. PHỤC TRUYỀN LUẬT LỆ.JSON' },
      { name: 'GIÔ-SUÊ', filename: '6. GIÔ-SUÊ.JSON' },
      { name: 'CÁC THỦ LÃNH', filename: '7. CÁC THỦ LÃNH.JSON' },
      { name: 'RU-TƠ', filename: '8. RU-TƠ.JSON' },
      { name: 'I SA-MU-ÊN', filename: '9. I SA-MU-ÊN.JSON' },
      { name: 'II SA-MU-ÊN', filename: '10. II SA-MU-ÊN.JSON' },
      { name: 'I CÁC VUA', filename: '11. I CÁC VUA.JSON' },
      { name: 'II CÁC VUA', filename: '12. II CÁC VUA.JSON' },
      { name: 'I SỬ KÝ', filename: '13. I SỬ KÝ.JSON' },
      { name: 'II SỬ KÝ', filename: '14. II SỬ KÝ.JSON' },
      { name: 'Ê-XƠ-RA', filename: '15. Ê-XƠ-RA.JSON' },
      { name: 'NÊ-HÊ-MI', filename: '16. NÊ-HÊ-MI.JSON' },
      { name: 'Ê-XƠ-TÊ', filename: '17. Ê-XƠ-TÊ.JSON' },
      { name: 'GIÓP', filename: '18. GIÓP.JSON' },
      { name: 'THÁNH THI', filename: '19. THÁNH THI.JSON' },
      { name: 'CHÂM NGÔN', filename: '20. CHÂM NGÔN.JSON' },
      { name: 'GIẢNG SƯ', filename: '21. GIẢNG SƯ.JSON' },
      { name: 'NHÃ CA', filename: '22. NHÃ CA.JSON' },
      { name: 'Ê-SAI', filename: '23. Ê-SAI.JSON' },
      { name: 'GIÊ-RÊ-MI', filename: '24. GIÊ-RÊ-MI.JSON' },
      { name: 'AI CA', filename: '25. AI CA.JSON' },
      { name: 'Ê-XÊ-CHI-ÊN', filename: '26. Ê-XÊ-CHI-ÊN.JSON' },
      { name: 'ĐA-NI-ÊN', filename: '27. ÐA-NI-ÊN.JSON' },
      { name: 'Ô-SÊ', filename: '28. Ô-SÊ.JSON' },
      { name: 'GIÔ-ÊN', filename: '29. GIÔ-ÊN.JSON' },
      { name: 'A-MỐT', filename: '30. A-MỐT.JSON' },
      { name: 'ÁP-ĐIA', filename: '31. ÁP-ÐIA.JSON' },
      { name: 'GIÔ-NA', filename: '32. GIÔ-NA.JSON' },
      { name: 'MI-CHÊ', filename: '33. MI-CHÊ.JSON' },
      { name: 'NA-HUM', filename: '34. NA-HUM.JSON' },
      { name: 'HA-BA-CÚC', filename: '35. HA-BA-CÚC.JSON' },
      { name: 'SÔ-PHÔ-NI', filename: '36. SÔ-PHÔ-NI.JSON' },
      { name: 'HA-GAI', filename: '37. HA-GAI.JSON' },
      { name: 'XA-CHA-RI', filename: '38. XA-CHA-RI.JSON' },
      { name: 'MA-LA-CHI', filename: '39. MA-LA-CHI.JSON' },
    ],
  },
  {
    id: 'new-testament',
    label: 'Tân Ước',
    books: [
      { name: 'MA-THI-Ơ', filename: '1. MA-THI-Ơ.JSON' },
      { name: 'MÁC', filename: '2. MÁC.JSON' },
      { name: 'LU-CA', filename: '3. LU-CA.JSON' },
      { name: 'GIĂNG', filename: '4. GIĂNG.JSON' },
      { name: 'CÔNG VỤ CỦA CÁC SỨ ĐỒ', filename: '5. CÔNG VỤ CỦA CÁC SỨ ĐỒ.JSON' },
      { name: 'RÔ-MA', filename: '6. RÔ-MA.JSON' },
      { name: 'I CÔ-RINH-TÔ', filename: '7. I CÔ-RINH-TÔ.JSON' },
      { name: 'II CÔ-RINH-TÔ', filename: '8. II CÔ-RINH-TÔ.JSON' },
      { name: 'GA-LA-TI', filename: '9. GA-LA-TI.JSON' },
      { name: 'Ê-PHÊ-SÔ', filename: '10. Ê-PHÊ-SÔ.JSON' },
      { name: 'PHI-LÍP', filename: '11. PHI-LÍP.JSON' },
      { name: 'CÔ-LÔ-SE', filename: '12. CÔ-LÔ-SE.JSON' },
      { name: 'I THÊ-SA-LÔ-NI-CA', filename: '13. I THÊ-SA-LÔ-NI-CA.JSON' },
      { name: 'II THÊ-SA-LÔ-NI-CA', filename: '14. II THÊ-SA-LÔ-NI-CA.JSON' },
      { name: 'I TI-MÔ-THÊ', filename: '15. I TI-MÔ-THÊ.JSON' },
      { name: 'II TI-MÔ-THÊ', filename: '16. II TI-MÔ-THÊ.JSON' },
      { name: 'TÍT', filename: '17. TÍT.JSON' },
      { name: 'PHI-LÊ-MÔN', filename: '18. PHI-LÊ-MÔN.JSON' },
      { name: 'HÊ-BƠ-RƠ', filename: '19. HÊ-BƠ-RƠ.JSON' },
      { name: 'GIA-CƠ', filename: '20. GIA-CƠ.JSON' },
      { name: 'I PHI-RƠ', filename: '21. I PHI-RƠ.JSON' },
      { name: 'II PHI-RƠ', filename: '22. II PHI-RƠ.JSON' },
      { name: 'I GIĂNG', filename: '23. I GIĂNG.JSON' },
      { name: 'II GIĂNG', filename: '24. II GIĂNG.JSON' },
      { name: 'III GIĂNG', filename: '25. III GIĂNG.JSON' },
      { name: 'GIU-ĐE', filename: '26. GIU-ÐE.JSON' },
      { name: 'KHẢI HUYỀN', filename: '27. KHẢI HUYỀN.JSON' },
    ],
  },
]
